# Travis CI setup for OpenFOAM-dev adapted from
# https://openfoamwiki.net/index.php/Installation/Linux/OpenFOAM-dev/Ubuntu#Ubuntu_14.04

sudo: required
dist: trusty
language: cpp

env:
  global:
    - REPO_DIR=$PWD
    - targetType=libso

before_install:
    - sudo apt-get install -qq git-core build-essential binutils-dev cmake flex bison zlib1g-dev qt4-dev-tools libqt4-dev libqtwebkit-dev gnuplot libreadline-dev libncurses-dev libxt-dev libopenmpi-dev openmpi-bin libboost-system-dev libboost-thread-dev libgmp-dev libmpfr-dev python python-dev
    - mkdir ~/OpenFOAM
    - cd ~/OpenFOAM
    - git clone https://github.com/OpenFOAM/ThirdParty-dev.git
    - cd ThirdParty-dev
    - mkdir download
    - wget -P download https://gforge.inria.fr/frs/download.php/file/34099/scotch_6.0.3.tar.gz
    - wget -P download https://github.com/CGAL/cgal/releases/download/releases%2FCGAL-4.7/CGAL-4.7.tar.xz
    - tar -xzf download/scotch_6.0.3.tar.gz
    - tar -xJf download/CGAL-4.7.tar.xz

install:
    # Move this repo into the correct directory
    - mv $REPO_DIR ~/OpenFOAM
    - source $HOME/OpenFOAM/OpenFOAM-dev/etc/bashrc
    - cd $WM_THIRD_PARTY_DIR
    - export QT_SELECT=qt4
    - ./Allwmake
    - cd $WM_PROJECT_DIR
    # Compile wmake support applications
    - (cd wmake/src && make)
    # Move into src dir
    - cd $WM_PROJECT_DIR/src
    # Update OpenFOAM version strings if required
    - wmakePrintBuild -check || /bin/rm -f OpenFOAM/Make/*/global.? 2>/dev/null
    # Start building libraries
    - wmakeLnInclude OpenFOAM
    - wmakeLnInclude OSspecific/${WM_OSTYPE:-POSIX}
    - Pstream/Allwmake $targetType $*
    - OSspecific/${WM_OSTYPE:-POSIX}/Allwmake $*
    - wmake $targetType OpenFOAM
    - wmake $targetType fileFormats
    - wmake $targetType surfMesh
    - wmake $targetType triSurface
    - wmake $targetType meshTools
    - wmake $targetType edgeMesh

before_script:
    - source $HOME/OpenFOAM/OpenFOAM-dev/etc/bashrc

script:
    - cd $FOAM_TUTORIALS
    - ./Alltest
