# Travis CI setup for OpenFOAM
# Code style is checked only, since build times exceed Travis limits

sudo: required
dist: trusty
language: cpp

before_install:
    - sudo apt-get install vera++

script:
    - git clone https://github.com/petebachant/foamStyleCheck.git
    - ./foamStyleCheck/checkStyle
